kubeVersion: ">=1.24.0-0"
apiVersion: v2
name: requestrr
version: 8.1.5
appVersion: 2.1.4
description: Requestrr is a chatbot used to simplify using services like Sonarr/Radarr/Ombi via the use of chat.
home: https://truecharts.org/charts/stable/requestrr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/requestrr.png
deprecated: false
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/requestrr
  - https://ghcr.io/linuxserver/requestrr
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
keywords:
  - requestrr
dependencies:
  - name: common
    version: 17.2.21
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
annotations:
  max_scale_version: 23.10.2
  min_scale_version: 23.10.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: incubator
  truecharts.org/max_helm_version: "3.13"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
type: application
